apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: https://github.com/SanTheEagle/podeapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports: 
        - containerPort: 80
        livenessProbe:
          exec:
            command:
              - pwsh
              - Command
              - Invoke-WebRequest -Uri http://localhost:80